---
categories:
- name: Armadi Refrigerati TN
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/EPF3485.jpg"
  url: "/products/armadi-refrigerati-tn/"
- name: Armadi Refrigerati BT
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/mcf8605.jpg"
  url: "/products/armadi-refrigerati-bt/"
- name: Vetrine Refrigerate
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  url: "/products/vetrine-refrigerate/"
- name: Banchi Pizza
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/EPF3485.jpg"
  url: "/products/banchi-pizza/"
- name: Saladettes
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/mcf8605.jpg"
  url: "/products/saladettes/"
- name: Catering Equipment
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  url: "/products/catering-equipment/"
- name: Teglie Gastronorm
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  url: "/products/teglie-gastronorm/"
- name: Vetrine
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  url: "/products/vetrine/"
home-specials:
- name: Prova
  card-color: lightcoral
  description: Provoinasdjw
  icon: Provaprova
  url:
- name: Prova
  card-color: lightgreen
  description: Provoinasdjw
  icon: Provaprova
  url:
- name: Prova
  card-color: lightpink
  description: Provoinasdjw
  icon: Provaprova
  url:
- name: Prova
  card-color: lightblue
  description: Provoinasdjw
  icon: Provaprova
  url:
menus:
- name: news
  url: "/news/"
- name: products
  url: "/products/"
- name: specials
  url: "/specials/"
- name: expo
  url: "/expo/"
- name: about
  url: "/about/"
- name: contact
  url: "/contact/"
