---
categories:
- img: "/assets/img/products/MBF8116.jpg"
  name: Armadi Refrigerati TN
  url: "/products/armadi-refrigerati-tn/"
- img: "/assets/img/products/MBF8117 (2).jpg"
  name: Armadi Refrigerati BT
  url: "/products/armadi-refrigerati-bt/"
- img: "/assets/img/products/vrx-glass.jpg"
  name: Vetrine Refrigerate
  url: "/products/vetrine-refrigerate/"
- img: "/assets/img/products/EPF3480 (2).jpg"
  name: Banchi Pizza
  url: "/products/banchi-pizza/"
- img: "/assets/img/products/ESL3853.jpg"
  name: Saladettes
  url: "/products/saladettes/"
- img: "/assets/img/products/AT90512-2.jpg"
  name: Catering Equipment
  url: "/products/catering-equipment/"
- img: "/assets/img/products/11100&11020.jpg"
  name: Teglie Gastronorm
  url: "/products/teglie-gastronorm/"
- img: "/assets/img/products/esl3831-34.jpg"
  name: Showcase
  url: "/products/showcase/"
certifications:
- img: "/assets/img/certifications/SGS_ISO_14001.png"
  name: ISO 14001
- img: "/assets/img/certifications/SGS_ISO_9001.png"
  name: ISO 9001
- img: "/assets/img/certifications/energy_star.png"
  name: ENERGY STAR
- img: "/assets/img/certifications/ce.png"
  name: CE
- img: "/assets/img/certifications/ROHS.png"
  name: RoHS
- img: "/assets/img/certifications/cb.png"
  name: CB
- img: "/assets/img/certifications/MEPS.png"
  name: MEPS
- img: "/assets/img/certifications/NSF.png"
  name: NSF
- img: "/assets/img/certifications/ETL.png"
  name: ETL
- img: "/assets/img/certifications/PSE.png"
  name: PSE
home-specials:
- card-color: lightcoral
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url:
- card-color: lightgreen
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url:
- card-color: lightpink
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url:
- card-color: lightblue
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url:
menus:
- name: prodotti
  url: "/products/"
- name: news
  url: "/news/"
- name: expo
  url: "/under-construction/"
- name: download
  url: "/under-construction/"
- name: about
  url: "/about/"
- name: contatti
  url: "/under-construction/"
