---
categories:
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/EPF3485.jpg"
  name: Armadi Refrigerati TN
  url: 
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/mcf8605.jpg"
  name: Armadi Refrigerati BT
  url: 
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  name: Vetrine Refrigerate
  url: 
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/EPF3485.jpg"
  name: Banchi Pizza
  url: 
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/mcf8605.jpg"
  name: Saladettes
  url: 
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  name: Catering Equipment
  url: 
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  name: Teglie Gastronorm
  url: 
- description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  img: "/assets/img/products/esl3831-34.jpg"
  name: Vetrine
  url: 
home-specials:
- card-color: lightcoral
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url: 
- card-color: lightgreen
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url: 
- card-color: lightpink
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url: 
- card-color: lightblue
  description: Provoinasdjw
  icon: Provaprova
  name: Prova
  url: 
menus:
- name: news
  url: "/news/"
- name: products
  url: "/products/"
- name: specials
  url: "/specials/"
- name: expo
  url: "/expo/"
- name: about
  url: "/about/"
- name: contact
  url: "/contact/"
